# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e74efa2c7560ee740bf5d0acecfafa5b266a4769e5b8adf7d9577a45c24f76bf5aeaae5d57128585ce611e38a7e688a6b9fe0a1e2d40e08f75fd4a86dcafbb1

test:
  secret_key_base: c2a277fac34902782ed1c12e45a7289983006847da52f05ec94932ccec1edd7365e191d2a43714c3e1cee1619e8af49cab25af645a97e3069a2c05a83be5b294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
