# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql
  encoding: utf8
  database: api
  reconnect: false
  pool: 5
  username: root
  password: "54486048"
  host: rauldb.cxk9jzkgrnud.us-west-2.rds.amazonaws.com
  port: 3306
test:
  adapter: mysql
  encoding: utf8
  database: api
  reconnect: false
  pool: 5
  username: root
  password: "54486048"
  host: rauldb.cxk9jzkgrnud.us-west-2.rds.amazonaws.com
  port: 3306
production:
  adapter: mysql
  encoding: utf8
  database: api
  reconnect: false
  pool: 5
  username: root
  password: "54486048"
  host: rauldb.cxk9jzkgrnud.us-west-2.rds.amazonaws.com
  port: 3306